# Generated by Django 3.2.9 on 2021-11-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
                ('type_of', models.CharField(choices=[('#', 'A'), ('##', 'B'), ('###', 'C')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NodeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('titulos', models.ManyToManyField(to='Text.Title')),
            ],
        ),
    ]
