# Generated by Django 3.2.9 on 2021-11-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetext',
            name='tipo_texto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='Text.typeoftext'),
            preserve_default=False,
        ),
    ]
