# Generated by Django 3.2.9 on 2021-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0003_nodetext_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetext',
            name='text',
            field=models.TextField(max_length=1500),
        ),
    ]
