# Generated by Django 3.2.9 on 2021-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0005_nodetext_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetext',
            name='publicavel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodetext',
            name='sub_titulo',
            field=models.CharField(default='subtitle', max_length=100),
            preserve_default=False,
        ),
    ]
