# Generated by Django 3.2.9 on 2021-11-29 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Text', '0006_auto_20211128_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetext',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
