name: Django CI

on:
  push:
    branches: [ master, develop, feature/test* ]
  pull_request:
    branches: [ master, develop ]

env:
  SECRET_KEY: o9ay-qj9zls73ngg_a0q#*72w%ik^of5&5auke2m-&*bjkjfx-
  DEBUG: 'True'
  DATABASE_URL: sqlite://$(pwd)/db.sqlite3
  CC_TEST_REPORTER_ID: 0556ee132ec46b9730042a946dc5c1af7f642a2ce86eff2e3ea86ce8ace05d0a

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2      
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic
    - name: Run Tests
      run: |
        coverage run manage.py test
    - name: coverage
      uses: paambaati/codeclimate-action@v3.0.0
      with:
        coverageCommand: coverage report